aanmelden/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .src import views
from .src import api

urlpatterns = [
    path("admin/", admin.site.urls),
    path("main/", views.Main.as_view(), name="main"),
    path("register/day/<str:day>/<str:pod>", views.Register.as_view(), name="register"),
    path(
        "register/future/<str:date>/<str:day>/<str:pod>",
        views.RegisterFuture.as_view(),
        name="register-future",
    ),
    path("register/seen/<int:pk>/<str:seen>", views.MarkAsSeen.as_view(), name="seen"),
    path(
        "register/manual/<str:day>/<str:pod>",
        views.RegisterManual.as_view(),
        name="register-manual",
    ),
    path(
        "deregister/day/<str:day>/<str:pod>",
        views.DeRegister.as_view(),
        name="deregister",
    ),
    path(
        "deregister/future/<str:date>/<str:day>/<str:pod>",
        views.DeRegisterFuture.as_view(),
        name="deregister-future",
    ),
    path("full/day/<str:day>/<str:pod>", views.Full.as_view(), name="full"),
    path("only_once/", views.OnlyOnce.as_view(), name="only_once"),
    path("stripcard_full/", views.StripcardFull.as_view(), name="stripcard_full"),
    path("report/", views.Report.as_view(), name="report"),
    path("calendar/", views.Calendar.as_view(), name="calendar"),
    path("logoff/", views.LogoffView.as_view(), name="logoff"),
    path("api/v2/free", api.FreeV2.as_view()),
    path("api/v1/mac_event", api.MacEvent.as_view()),
    path(
        "api/v2/is_present/<str:day>/<str:pod>/<str:userid>", api.IsPresentV2.as_view()
    ),
    path("api/v2/are_present/<str:day>/<str:pod>", api.ArePresentV2.as_view()),
    path(
        "api/v1/present_since_date/<str:userid>/<int:year>/<int:month>/<int:day>",
        api.PresentSinceDate.as_view(),
    ),
    path("api/v1/slots", api.Slots.as_view()),
    path("api/v1/register/<str:day>/<str:pod>", api.Register.as_view()),
    path("api/v1/register/<str:day>/<str:pod>/<str:date>", api.Register.as_view()),
    path("api/v1/deregister/<str:day>/<str:pod>", api.DeRegister.as_view()),
    path("api/v1/deregister/<str:day>/<str:pod>/<str:date>", api.DeRegister.as_view()),
    path(
        "api/v1/register_manual/<str:day>/<str:pod>/<str:pk>",
        api.RegisterManual.as_view(),
    ),
    path("api/v1/future", api.FutureUpdate.as_view()),
    path("api/v1/seen/<int:pk>/<str:seen>", api.MarkSeen.as_view()),
    re_path(r"oauth/.*", views.LoginResponseView.as_view()),
    path("", views.LoginView.as_view(), name="login"),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

aanmelden/src/models.py
import datetime

from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.forms.models import model_to_dict
from django.utils import timezone

DAY_NUMBERS = {"mon": 0, "tue": 1, "wed": 2, "thu": 3, "fri": 4, "sat": 5, "sun": 6}

POD_CHOICES = (
    ("m", "Ochtend"),
    ("a", "Middag"),
    ("e", "Avond"),
)

DAY_CHOICES = (
    ("mon", "Maandag"),
    ("tue", "Dinsdag"),
    ("wed", "Woensdag"),
    ("thu", "Donderdag"),
    ("fri", "Vrijdag"),
    ("sat", "Zaterdag"),
    ("sun", "Zondag"),
)

DjangoUser = get_user_model()


class DjoUser(DjangoUser):
    class Meta:
        proxy = True
        ordering = ["first_name", "last_name"]

    @staticmethod
    def is_begeleider(account_type):
        types = account_type.split(",")
        return (
            "begeleider" in types
            or "aspirant_begeleider" in types
            or "ondersteuning" in types
        )

    @staticmethod
    def has_strippenkaart(account_type):
        types = account_type.split(",")
        return "strippenkaart" in types

    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.username})"


class UserInfo(models.Model):
    user: DjoUser = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    days = models.IntegerField(default=1, null=False)
    account_type = models.CharField(max_length=100, default="", null=False)
    stripcard_used = models.IntegerField(default=0, null=False)
    stripcard_count = models.IntegerField(default=0, null=False)
    stripcard_expires = models.DateField(
        default=timezone.datetime(year=2099, month=1, day=1).date(), null=False
    )

    def __str__(self):
        return f"User details for {self.user}"


class Slot(models.Model):
    class Meta:
        unique_together = ["name", "pod"]

    name = models.CharField(max_length=3, choices=DAY_CHOICES)
    pod = models.CharField(choices=POD_CHOICES, max_length=1)
    description = models.CharField(max_length=255)
    enabled = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.name}-{self.pod}: {self.description}"

    @property
    def date(self):
        today = datetime.date.today()
        return today + datetime.timedelta(
            (DAY_NUMBERS[self.name] - today.weekday()) % 7
        )

    @property
    def closed(self):
        return SpecialDate.is_closed(self.date, self.pod)

    @property
    def available(self):
        return Presence.slots_available(self.date, self.pod)

    @property
    def taken(self):
        return Presence.slots_taken(self.date, self.pod)

    @property
    def tutor_count(self):
        return Presence.get_tutor_count(self.date, self.pod)

    @property
    def tutors(self):
        return list(
            Presence.objects.filter(
                date=self.date, pod=self.pod, user__is_superuser=True
            ).values_list("user__first_name", flat=True)
        )

    @property
    def announcement(self):
        try:
            special_date = SpecialDate.objects.get(date=self.date, pod=self.pod)
        except SpecialDate.DoesNotExist:
            return ""
        return special_date.announcement

    def is_registered(self, user):
        return (
            Presence.objects.filter(user=user, date=self.date, pod=self.pod).count() > 0
        )

    @staticmethod
    def get_enabled_slots(user=None):
        slots = Slot.objects.filter(enabled=True)
        available_slots = []
        for slot in slots:
            available_slot = model_to_dict(slot)
            available_slot.pop("id")
            for field in [
                "date",
                "taken",
                "available",
                "closed",
                "tutor_count",
                "tutors",
                "announcement",
            ]:
                available_slot[field] = getattr(slot, field)
            if user:
                available_slot["is_registered"] = slot.is_registered(user)
            available_slots.append(available_slot)
        return available_slots

    @staticmethod
    def get(day: str, pod: str):
        try:
            slot = Slot.objects.get(name=day, pod=pod)
        except Slot.DoesNotExist:
            slot = None
        return slot


class Presence(models.Model):
    class Meta:
        unique_together = ("user", "date", "pod")
        indexes = [
            models.Index(fields=["date", "pod"]),
            models.Index(fields=["date", "user"]),
            models.Index(fields=["date", "user", "pod"]),
            models.Index(fields=["date"]),
        ]

    @staticmethod
    def get_tutor_count(date, pod=None):
        if pod:
            return Presence.objects.filter(
                date=date, pod=pod, user__is_superuser=True
            ).count()
        return Presence.objects.filter(date=date, user__is_superuser=True).count()

    @staticmethod
    def slots_available(on_date, pod=None):
        try:
            special_date = SpecialDate.objects.get(date=on_date, pod=pod)
        except SpecialDate.DoesNotExist:
            try:
                special_date = SpecialDate.objects.get(date=on_date, pod=None)
            except SpecialDate.DoesNotExist:
                special_date = None

        slots_available = 0
        if special_date and special_date.free_slots >= 0:
            slots_available = special_date.free_slots
            if special_date.closed:
                slots_available = 0
        else:
            # Add more slots depending on nr of tutors
            tutor_count = Presence.get_tutor_count(on_date, pod)
            for amount, extra in settings.SLOT_LEVELS.items():
                if tutor_count >= amount:
                    slots_available += extra

        return slots_available - Presence.slots_taken(on_date, pod)

    @staticmethod
    def slots_taken(on_date, pod=None):
        return Presence.objects.filter(
            date=on_date, pod=pod, user__is_superuser=False
        ).count()

    def __str__(self):
        return f"{self.date}/{self.pod}: {self.user}"

    SEEN_BY_CHOICES = (("mac", "Mac Adres"), ("manual", "Handmatig Aangemeld"))

    user = models.ForeignKey(DjoUser, models.CASCADE)
    date = models.DateField()
    pod = models.CharField(choices=POD_CHOICES, max_length=1, null=True)
    seen = models.BooleanField(default=False)
    seen_by = models.CharField(
        max_length=6, choices=SEEN_BY_CHOICES, default="manual", null=False
    )


class SpecialDate(models.Model):
    date = models.DateField()
    free_slots = models.IntegerField()
    pod = models.CharField(choices=POD_CHOICES, max_length=1, null=True, blank=True)
    announcement = models.TextField(null=True, blank=True)
    closed = models.BooleanField()

    @staticmethod
    def is_closed(on_date, pod=None):
        try:
            special_date = SpecialDate.objects.get(date=on_date, pod=pod)
        except SpecialDate.DoesNotExist:
            try:
                special_date = SpecialDate.objects.get(date=on_date, pod=None)
            except SpecialDate.DoesNotExist:
                special_date = None

        closed = False
        if special_date:
            closed = special_date.closed

        return closed

    def __str__(self):
        return f"{self.date}, Pod: {self.pod}, Slots: {self.free_slots}, Closed: {self.closed}"


class MacAddress(models.Model):
    class Meta:
        verbose_name_plural = "Mac Addresses"
        order_with_respect_to = "user"

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}: {self.mac}"

    user = models.ForeignKey(DjoUser, models.CASCADE)
    mac = models.CharField(max_length=17, null=False, unique=True)

aanmelden/templates/already_seen.html
{% extends 'base/base_status.html' %}

{% block icon %}line-md:watch-twotone{% endblock %}
{% block title %}Je bent al aanwezig gemeld!{% endblock %}
{% block description %}Je kunt je dus niet meer afmelden...{% endblock %}

aanmelden/templates/calendar.html
{% extends 'base/base_main.html' %}
{% load static %}

{% block head %}
{{ block.super }}
<script defer src="{% static 'js/calendar.js' %}?v=1"></script>
{{ entries|json_script:"entries" }}
{{ slots|json_script:"slots" }}
{% endblock %}

{% block description %}
Je kunt je hier met de kalender aanmelden.
{% endblock %}

{% block content %}
{{ block.super }}

<div class="container max-w-lg">
    <!-- calendar -->
    <div class="d-flex justify-content-between align-items-center mb-2">
        <div id="calendar-title" class="fw-bold text-center text-capitalize lead"></div>
        <div class="d-flex gap-2">
            <button class="btn btn-primary" onclick="nextMonth(-1)">
                <iconify-icon noobserver icon="line-md:arrow-left" inline role="img" alt="vorige maand"></iconify-icon>
            </button>
            <button class="btn btn-primary" onclick="resetMonth()">
                <iconify-icon noobserver icon="line-md:home-md" inline role="img" alt="deze maand"></iconify-icon>
            </button>
            <button class="btn btn-primary" onclick="nextMonth(1)">
                <iconify-icon noobserver icon="line-md:arrow-right" inline role="img" alt="volgende maand"></iconify-icon>
            </button>
        </div>
    </div>
    <table class="table table-bordered table-layout-fixed">
        <thead class="text-center table-active">
            <tr>
                <th class="p-2">Ma</th>
                <th class="p-2">Di</th>
                <th class="p-2">Wo</th>
                <th class="p-2">Do</th>
                <th class="p-2">Vr</th>
                <th class="p-2">Za</th>
                <th class="p-2">Zo</th>
            </tr>
        </thead>
        <tbody id="calendar-body"></tbody>
    </table>
</div>
{% endblock %}

aanmelden/templates/deregistered.html
{% extends 'base/base_status.html' %}

{% block icon %}line-md:close-circle-twotone{% endblock %}
{% block title %}Je hebt je afgemeld.{% endblock %}
{% block description %}{{ slot.description }}{% endblock %}

aanmelden/templates/full.html
{% extends 'base/base_status.html' %}

{% block icon %}line-md:person-off-twotone{% endblock %}
{% block title %}Er is geen plek meer!{% endblock %}
{% block description %}{{ slot.description }}{% endblock %}

aanmelden/templates/main.html
{% extends 'base/base_main.html' %}
{% load static %}

{% block head %}
{{ block.super }}
<script src="{% static 'js/main-reload.js' %}?v=1"></script>
{% endblock %}

{% block description %}
Je kunt je hier aanmelden voor DJO voor aankomend weekend.
{% endblock %}

{% block content %}
{{ block.super }}
<div class="container text-center">
    {% if user.userinfo.stripcard_count > 0 %}
    <div class="alert alert-primary mb-4">
        <iconify-icon noobserver icon="line-md:confirm-circle" inline aria-hidden="true"></iconify-icon>
        Je strippenkaart is
        <strong>{{ user.userinfo.stripcard_used }}</strong>
        van de
        <strong>{{ user.userinfo.stripcard_count }}</strong>
        keer gebruikt en geldig tot <strong>{{ user.userinfo.stripcard_expires }}</strong>.
    </div>
    {% endif %}
    
    <div class="row">
        {% for slot in slots %}
        {% if not slot.closed %}
        <div class="col-md">
            <div class="card mb-3 {% if slot.is_registered %}border-primary{% endif %}">
                <!-- header status texts -->
                <div class="card-header small py-2 {% if slot.is_registered %}text-primary{% endif %}">
                    {% if slot.is_registered %}
                    <iconify-icon noobserver icon="line-md:pencil" inline aria-hidden="true"></iconify-icon>
                    Aangemeld! &bull;
                    {% endif %}
                    <iconify-icon noobserver icon="line-md:calendar" inline role="img" alt="datum:"></iconify-icon>
                    {{ slot.date }}
                </div>
                <div class="card-body">
                    <!-- announcement -->
                    {% if slot.announcement %}
                    <div class="alert alert-primary mb-4">
                        <iconify-icon noobserver icon="line-md:bell-loop" inline role="img" alt="announcement:"></iconify-icon>
                        {{ slot.announcement | safe }}
                    </div>
                    {% endif %}

                    <!-- slot description -->
                    <h5 class="card-title mt-2 fw-bold">
                        {% if slot.is_registered %}
                        <iconify-icon noobserver icon="line-md:confirm-circle" inline class="text-primary" aria-hidden="true"></iconify-icon>
                        {% else %}
                        <iconify-icon noobserver icon="line-md:chevron-right-circle" inline aria-hidden="true"></iconify-icon>
                        {% endif %}
                        {{ slot.description }}
                    </h5>

                    <!-- available spots -->
                    <div class="card-text mb-4">
                        Er {{ slot.available|pluralize:"is,zijn" }}
                        <strong>
                        {% if slot.available < 1 %}
                        geen
                        {% else %}
                        {{ slot.available }}
                        {% endif %}
                        </strong>
                        plek{{ slot.available|pluralize:"ken"}} beschikbaar.
                    </div>
                    
                    <!-- register buttons -->
                    <div>
                        {% if slot.is_registered %}                  
                        <a class="btn btn-outline-primary" href="{% url 'deregister' slot.name slot.pod %}">
                            <iconify-icon noobserver icon="line-md:logout" inline aria-hidden="true"></iconify-icon>
                            Afmelden
                        </a>
                        {% elif slot.available == 0 %}
                        <a class="btn btn-outline-primary disabled">
                            <iconify-icon noobserver icon="line-md:cancel" inline aria-hidden="true"></iconify-icon>
                            Aanmelden
                        </a>
                        {% else %}
                        <a class="btn btn-primary" href="{% url 'register' slot.name slot.pod %}">
                            <iconify-icon noobserver icon="line-md:login" inline aria-hidden="true"></iconify-icon>
                            Aanmelden
                        </a>
                        {% endif %}
                    </div>
                </div>
                <div class="card-footer small py-2 {% if slot.is_registered %}text-primary{% endif %}">
                    <iconify-icon noobserver icon="line-md:account" inline aria-hidden="true"></iconify-icon>
                    {% if slot.tutors %}
                    <strong>Begeleiders:</strong>
                    {{ slot.tutors|join:", "|default:"-" }}
                    {% else %}
                    <span class="text-muted">Er zijn (nog) geen begeleiders aanwezig.</span>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock %}

aanmelden/templates/only_once.html
{% extends 'base/base_status.html' %}

{% block icon %}line-md:calendar{% endblock %}
{% block title %}Je hebt je dit weekend al aangemeld!{% endblock %}
{% block description %}
<ul class="text-start">
    <li><u>Van dag wisselen?</u> Meld je bij de andere dag eerst af.</li>
    <li><u>Op beide dagen komen?</u> Vraag dan een <a href="https://www.djoamersfoort.nl/organisatie/bestuur/" target="_blank" class="link-primary">bestuurslid</a> om toestemming.</li>
</ul>
{% endblock %}

aanmelden/templates/register_manual.html
{% extends 'base/base_status.html' %}
{% load static %}
{% load widget_tweaks %}

{% block icon %}line-md:person-add-twotone{% endblock %}
{% block title %}Gebruiker Handmatig Aanmelden{% endblock %}
{% block description %}{{ slot.description }}{% endblock %}

{% block content %}
{{ block.super }}
<form method="post">
    <div class="container d-flex justify-content-center">
        <div class="form-group w-100 max-w-md">
            {% csrf_token %}
            
            <div class="mb-3">
                <label class="form-label" for="id_user">Gebruiker</label>
                {% render_field form.user title="Lid" class+="form-control" %}
            </div>

            <input class="btn btn-primary w-100" type="submit" value="Aanmelden">
        </div>
    </div>
</form>
{% endblock %}

aanmelden/templates/registered.html
{% extends 'base/base_status.html' %}
{% load static %}

{% block head %}
{{ block.super }}
<script src="{% static 'js/cdn/confetti.browser.min.js' %}?v=1"></script>
<script src="{% static 'js/confetti.js' %}?v=1"></script>
{% endblock %}

{% block icon %}line-md:confirm-circle-twotone{% endblock %}
{% block title %}Je hebt je aangemeld!{% endblock %}
{% block description %}{{ slot.description }}{% endblock %}

aanmelden/templates/report.html
{% extends 'base/base_main.html' %}
{% load mathfilters %}
{% load static %}

{% block head %}
{{ block.super }}
<script src="{% static 'js/report-reload.js' %}?v=1"></script>
{% endblock %}

{% block description %}
Een overzicht van leden voor de aankomende vrijdag en zaterdag.
{% endblock %}

{% block content %}
{{ block.super }}
<div class="container text-center">
    <div class="row">
        {% for slot in slots %}
        {% if not slot.closed %}
        <div class="col-md">
            <div class="card mb-3 {% if slot.is_registered %}border-primary{% endif %}">
                <!-- header status texts -->
                <div class="card-header py-2 small {% if slot.is_registered %}text-primary{% endif %}">
                    {% if slot.is_registered %}
                    <iconify-icon noobserver icon="line-md:pencil" inline aria-hidden="true"></iconify-icon>
                    Aangemeld! &bull;
                    {% endif %}
                    <iconify-icon noobserver icon="line-md:calendar" inline role="img" alt="datum:"></iconify-icon>
                    {{ slot.date }}
                </div>
                <div class="card-body">
                    <!-- announcement -->
                    {% if slot.announcement %}
                    <div class="alert alert-primary mb-4">
                        <iconify-icon noobserver icon="line-md:bell-loop" inline role="img" alt="announcement:"></iconify-icon>
                        {{ slot.announcement | safe }}
                    </div>
                    {% endif %}

                    <!-- slot description -->
                    <h5 class="card-title mt-2 fw-bold">
                        {% if slot.is_registered %}
                        <iconify-icon noobserver icon="line-md:confirm-circle" inline class="text-primary" aria-hidden="true"></iconify-icon>
                        {% else %}
                        <iconify-icon noobserver icon="line-md:chevron-right-circle" inline aria-hidden="true"></iconify-icon>
                        {% endif %}
                        {{ slot.description }}
                    </h5>
                    
                    <!-- available spots -->
                    <div class="card-text mb-3">
                        <div>
                            Er {{ slot.available|pluralize:"is,zijn" }}
                            {% if slot.available == 0 %}
                            <span class="badge text-bg-warning">0 / {{ slot.available|add:slot.taken }}</span>
                            {% elif slot.available < 0 %}
                            <span class="badge text-bg-danger">0 / {{ slot.available|add:slot.taken }}</span>
                            {% else %}
                            <span class="badge text-bg-primary">{{ slot.available }} / {{ slot.available|add:slot.taken }}</span>
                            {% endif %}
                            slot{{ slot.available|pluralize}}
                            {% if slot.available < 0 %}
                            beschikbaar, <strong class="text-danger">{{ slot.available|abs }} te veel</strong>.
                            {% else %}
                            beschikbaar.
                            {% endif %}
                        </div>
                        <div>
                            Er {{ slot.tutor_count|pluralize:"is,zijn" }}
                            <span class="badge text-bg-primary">{{ slot.tutor_count }}</span>
                            begeleider{{ slot.tutor_count|pluralize}} aangemeld.
                        </div>
                    </div>

                    <!-- list of people -->
                    <div class="d-flex justify-content-center mb-4">
                        <div class="text-start">
                            {% for member in object_list %}
                            {% if member.date == slot.date and member.pod == slot.pod %}
                            {% if member.user.is_superuser %}
                            <div>
                                <iconify-icon noobserver icon="line-md:account" class="text-primary" inline role="img" alt="begeleider:"></iconify-icon>
                                {{ member.user.first_name }} {{ member.user.last_name }}
                            </div>
                            {% else %}
                            <div class="form-check">
                                <input
                                    type="checkbox"
                                    autocomplete="off"
                                    class="form-check-input"
                                    id="{{ member.id }}"
                                    data-request-url="{% url 'seen' member.id '::' %}"
                                    {% if member.seen %}checked{% endif %}
                                >
                                <label class="form-check-label" for="{{ member.id }}">
                                    {{ member.user.first_name }} {{ member.user.last_name }}
                                    {% if 'strippenkaart' in member.user.userinfo.account_type %}
                                    <span class="text-primary ms-1">
                                        <iconify-icon noobserver icon="line-md:check-list-3" inline role="img" alt="strippenkaart"></iconify-icon>
                                        {{ member.user.userinfo.stripcard_used }} / {{ member.user.userinfo.stripcard_count }}
                                    </span>
                                    {% endif %}
                                    {% if member.seen and member.seen_by == 'mac' %}
                                    <span class="text-primary ms-1">
                                        <iconify-icon noobserver icon="line-md:cloud" inline role="img" alt="aangemeld via MAC adres"></iconify-icon>
                                    </span>
                                    {% endif %}
                                </label>
                            </div>
                            {% endif %}
                            {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                    
                    <!-- register buttons -->
                    <div>
                        <a class="btn btn-primary" href="{% url 'register-manual' slot.name slot.pod %}">
                            <iconify-icon noobserver icon="line-md:person-add" inline aria-hidden="true"></iconify-icon>
                            Lid Aanmelden
                        </a>
                        
                        {% if slot.is_registered %}                  
                        <a class="btn btn-outline-primary" href="{% url 'deregister' slot.name slot.pod %}">
                            <iconify-icon noobserver icon="line-md:logout" inline aria-hidden="true"></iconify-icon>
                            Afmelden
                        </a>
                        {% else %}
                        <a class="btn btn-primary" href="{% url 'register' slot.name slot.pod %}">
                            <iconify-icon noobserver icon="line-md:login" inline aria-hidden="true"></iconify-icon>
                            Aanmelden
                        </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
</div>

{% endblock %}

aanmelden/templates/stripcard_full.html
{% extends 'base/base_status.html' %}

{% block icon %}line-md:clipboard-arrow-twotone{% endblock %}
{% block title %}Je strippenkaart is vol!{% endblock %}
{% block description %}
<div class="text-start">
    Je kunt je nu niet aanmelden. Je kan wel:
    <ul class="my-2">
        <li>Een nieuwe strippenkaart kopen</li>
        <li>Naar een regulier lidmaatschap omzetten</li>
    </ul>
    Stuur ons hiervoor <a href="mailto:info@djoamersfoort.nl">een email</a>.
</div>
{% endblock %}

aanmelden/templates/try_again_later.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container text-center">
    <div class="jumbotron mt-md-5 mt-3">
        <i class="fas fa-calendar-times fa-5x mt-3 text-primary"></i>
        <div class="mt-2 h-title">Helaas, je kunt je op dit moment nog niet aanmelden voor komende {% if view.kwargs.day == 'fri' %}vrijdag{% else %}zaterdag{% endif %}.</div>
        <p>Je was afgelopen {% if view.kwargs.day == 'fri' %}vrijdag{% else %}zaterdag{% endif %}
            aanwezig, waardoor je je deze keer pas vanaf aankomende woensdag kunt aanmelden. Vervelend, maar zo geven we alle DJO-ers een kans om aanwezig te zijn.</p>
        <div class="lead">Terug naar de <a href="{% url 'main' %}">homepage</a>.</div>
    </div>
</div>

{% endblock %}